modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
issueTrackerURL="https://github.com/nonamecrackers2/mob-battle-music/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/nonamecrackers2/mob-battle-music/1.20.1/update_checker.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-battle-music" #optional
#logoFile="examplemod.png" #optional
credits="TSEG" #optional
authors="${mod_authors}" #optional
#displayTest="IGNORE_ALL_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="crackerslib"
    mandatory=true
    versionRange="[0.1,)"
    ordering="NONE"
    side="BOTH"

#openGLVersion="[3.2,)"